/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PortfoliosRouteImport } from './routes/portfolios'
import { Route as InvestorGrievanceRouteImport } from './routes/investor-grievance'
import { Route as InvestorCharterRouteImport } from './routes/investor-charter'
import { Route as GrievancesRouteImport } from './routes/grievances'
import { Route as DisclosuresRouteImport } from './routes/disclosures'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosRoute = PortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorGrievanceRoute = InvestorGrievanceRouteImport.update({
  id: '/investor-grievance',
  path: '/investor-grievance',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorCharterRoute = InvestorCharterRouteImport.update({
  id: '/investor-charter',
  path: '/investor-charter',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievancesRoute = GrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosuresRoute = DisclosuresRouteImport.update({
  id: '/disclosures',
  path: '/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/disclosures': typeof DisclosuresRoute
  '/grievances': typeof GrievancesRoute
  '/investor-charter': typeof InvestorCharterRoute
  '/investor-grievance': typeof InvestorGrievanceRoute
  '/portfolios': typeof PortfoliosRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/disclosures': typeof DisclosuresRoute
  '/grievances': typeof GrievancesRoute
  '/investor-charter': typeof InvestorCharterRoute
  '/investor-grievance': typeof InvestorGrievanceRoute
  '/portfolios': typeof PortfoliosRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/disclosures': typeof DisclosuresRoute
  '/grievances': typeof GrievancesRoute
  '/investor-charter': typeof InvestorCharterRoute
  '/investor-grievance': typeof InvestorGrievanceRoute
  '/portfolios': typeof PortfoliosRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/disclaimer'
    | '/disclosures'
    | '/grievances'
    | '/investor-charter'
    | '/investor-grievance'
    | '/portfolios'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/disclaimer'
    | '/disclosures'
    | '/grievances'
    | '/investor-charter'
    | '/investor-grievance'
    | '/portfolios'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/disclaimer'
    | '/disclosures'
    | '/grievances'
    | '/investor-charter'
    | '/investor-grievance'
    | '/portfolios'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DisclosuresRoute: typeof DisclosuresRoute
  GrievancesRoute: typeof GrievancesRoute
  InvestorCharterRoute: typeof InvestorCharterRoute
  InvestorGrievanceRoute: typeof InvestorGrievanceRoute
  PortfoliosRoute: typeof PortfoliosRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios': {
      id: '/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof PortfoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor-grievance': {
      id: '/investor-grievance'
      path: '/investor-grievance'
      fullPath: '/investor-grievance'
      preLoaderRoute: typeof InvestorGrievanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor-charter': {
      id: '/investor-charter'
      path: '/investor-charter'
      fullPath: '/investor-charter'
      preLoaderRoute: typeof InvestorCharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievances': {
      id: '/grievances'
      path: '/grievances'
      fullPath: '/grievances'
      preLoaderRoute: typeof GrievancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosures': {
      id: '/disclosures'
      path: '/disclosures'
      fullPath: '/disclosures'
      preLoaderRoute: typeof DisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  DisclaimerRoute: DisclaimerRoute,
  DisclosuresRoute: DisclosuresRoute,
  GrievancesRoute: GrievancesRoute,
  InvestorCharterRoute: InvestorCharterRoute,
  InvestorGrievanceRoute: InvestorGrievanceRoute,
  PortfoliosRoute: PortfoliosRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
